package com.example.hashcartapp.constants;


public enum Category {
    ELECTRONICS, VEHICLES, BOOKS, JEWELLERY, SPECTACLES, DECOR, SWEETS, PETS, LAND, SHOPS, HOMES, CLOTHING, FURNITURE, STATIONARY, GAMES, TOYS, FOOD , DRINKS , KITCHENAPPLIANCES, MAKEUP;
}
